### ISSUE TITLE
README.md 작성

### ISSUE THREAD

**Issue by YeonSeong-Lee** [jiphyeonjeon-42/backend#192]
### 제안 내용
 README.md에서 더 많은 정보를 제공해주었으면 좋겠습니다.

- [x] 기술 스택 정리
- [x] 운영하고 있는 웹사이트 주소
- [x] #238
- [x] 바꿔야 할 내용 추가받음

**Comment by nyj001012** [comment]
# 🏠 [42서울의 도서관, 집현전]((https://42library.kr/))
<img alt="jiphyeonjeon_image" src="https://user-images.githubusercontent.com/79993356/180756135-0f622d3c-e5aa-4ac8-8d50-fa768aeaf5f9.png" width="70%"/>

1,000명 이상이 사용하는 42 SEOUL 공식 도서관 웹사이트입니다.

사용자와 사서님들에게 피드백을 매주 받는 것은 물론, 사이트에 대한 건의 사항을 42 Seoul 재단에서 직접 받기도 합니다.

매주 유지보수 팀이 도서관에 상주하여 해당 건의 사항을 해결합니다.

# 📚 집현전 Backend
집현전 백엔드 웹 서비스의 3rd Development 입니다.

# 💻 기술 스택
![typescript](https://img.shields.io/badge/TypeScript-^4.5.5-3178C6?logo=TypeScript) ![Express](https://img.shields.io/badge/Express-^4.17.2-000000?logo=Express) ![jest](https://img.shields.io/badge/Jest-^27.5.1-C21325?logo=Jest) ![.ENV](https://img.shields.io/badge/.ENV-^2.3.3-ECD53F?logo=.ENV) ![MySQL2](https://img.shields.io/badge/MySQL2-^2.3.3-4479A1?logo=MySQL) ![docker-compose](https://img.shields.io/badge/docker--compose-v2-2496ED?logo=Docker) ![swagger](https://img.shields.io/badge/swagger-3.x-85EA2D?logo=swagger)

# 🗒 ERD (Updated at 2022.10.26)
![erd_backend](https://user-images.githubusercontent.com/50291995/198007446-0259fd24-1b8a-4d40-a2b8-cb8cce2bddc2.png)

# 👥 Developers
- [jolim](https://github.com/evelon)
- [chanykim](https://github.com/naranghae)
- [tkim](https://github.com/kth2624)
- [jimin](https://github.com/jhMin95)
- [wocho](https://github.com/greenaloud)
- [seongyle](https://github.com/YeonSeong-Lee)
- [gilee](https://github.com/weg901127)
- [sechung](https://github.com/OverRaddit)
- [gshim]()
- [chanheki](https://github.com/chanhihi)
- [yena](https://github.com/nyj001012)

**Comment by nyj001012** [comment]
# 🏠 [42서울의 도서관, 집현전]((https://42library.kr/))
<img alt="jiphyeonjeon_image" src="https://user-images.githubusercontent.com/79993356/180756135-0f622d3c-e5aa-4ac8-8d50-fa768aeaf5f9.png" width="70%"/>

1,000명 이상이 사용하는 42 SEOUL 공식 도서관 웹사이트입니다.

사용자와 사서님들에게 피드백을 매주 받는 것은 물론, 사이트에 대한 건의 사항을 42 Seoul 재단에서 직접 받기도 합니다.

매주 유지보수 팀이 도서관에 상주하여 해당 건의 사항을 해결합니다.

# 📚 집현전 Backend
집현전 백엔드 웹 서비스의 3rd Development 입니다.

# 💻 기술 스택
![typescript](https://img.shields.io/badge/TypeScript-^4.5.5-3178C6?logo=TypeScript) ![Express](https://img.shields.io/badge/Express-^4.17.2-000000?logo=Express) ![jest](https://img.shields.io/badge/Jest-^27.5.1-C21325?logo=Jest) ![.ENV](https://img.shields.io/badge/.ENV-^2.3.3-ECD53F?logo=.ENV) ![MySQL2](https://img.shields.io/badge/MySQL2-^2.3.3-4479A1?logo=MySQL) ![docker-compose](https://img.shields.io/badge/docker--compose-v2-2496ED?logo=Docker) ![swagger](https://img.shields.io/badge/swagger-3.x-85EA2D?logo=swagger)

# 🗒 ERD (Updated at 2022.10.26)
![erd_backend](https://user-images.githubusercontent.com/50291995/198007446-0259fd24-1b8a-4d40-a2b8-cb8cce2bddc2.png)

# 👥 Developers
- [jolim](https://github.com/evelon)
- [chanykim](https://github.com/naranghae)
- [tkim](https://github.com/kth2624)
- [jimin](https://github.com/jhMin95)
- [wocho](https://github.com/greenaloud)
- [seongyle](https://github.com/YeonSeong-Lee)
- [gilee](https://github.com/weg901127)
- [sechung](https://github.com/middlefitting)
- [gshim](https://github.com/OverRaddit)
- [chanheki](https://github.com/chanhihi)
- [yena](https://github.com/nyj001012)

**Comment by nyj001012** [comment]
# comment
위에 걸 기본 틀로 해서 내용 덧붙이면 될 것 같아요. 추가로 기술 스택의 경우 package.json을 참고했는데, 더 추가했으면 하는 기술이 있다면 말씀해주세요 :)

# 추가하면 좋을 것 같은 내용
1. 기능 건의 시트 링크 걸기  
-> 42 인원들만 건의할 수 있게 해야한다면 readme에 넣는 게 좋을 것 같진 않아요.
2. 개발 인원 개발 회차 수에 따라 분류  
-> 1차 ~ 4차까지 분류해서 넣자니, 이전 분들 인트라 아이디와 깃허브 주소를 알아보려고 했는데 어렵네요. 의견 있으시다면 말씀해주세요.
3. 백엔드에서 개발한 것들  버전 별로 나열
-> 메이저 업데이트가 언제, 어떤 내용으로 이루어졌는지 등을 적어줘도 좋을 것 같아요

# todo 
- [x] sechung님 깃허브 링크 추가

**Comment by nyj001012** [comment]
> 방문자수(hits) 적용 시의 readme 예시입니다

# 🏠 [42서울의 도서관, 집현전]((https://42library.kr/))
<img alt="jiphyeonjeon_image" src="https://user-images.githubusercontent.com/79993356/180756135-0f622d3c-e5aa-4ac8-8d50-fa768aeaf5f9.png" width="70%"/>

![Hits](https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fgithub.com%2Fjiphyeonjeon-42%2Fbackend&count_bg=%23000000&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=hits&edge_flat=false)

1,000명 이상이 사용하는 42 SEOUL 공식 도서관 웹사이트입니다.

사용자와 사서님들에게 피드백을 매주 받는 것은 물론, 사이트에 대한 건의 사항을 42 Seoul 재단에서 직접 받기도 합니다.

매주 유지보수 팀이 도서관에 상주하여 해당 건의 사항을 해결합니다.
