### ISSUE TITLE
☂️ DTO 객체 만들고 적용하기

### ISSUE THREAD

**Issue by jimin52** [jiphyeonjeon-42/backend#447]
### 기능 설명

```[tasklist]
### DTO 만들기 및 적용
- [ ] #448
- [ ] Make Lending, Book, History DTO
- [ ] Make Reservation DTO
- [ ] Make Review, Like, Stock DTO
- [ ] Make Auth DTO
```

**Comment by scarf005** [comment]
contract에서 DTO를 생성 가능하므로 #543 으로 통합하였습니다.
