### ISSUE TITLE
☂️ 백엔드 API 타입스크립트 타입 정리 프로젝트

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#485]
### 제안 설명

- 현재 백엔드 API는 swagger docs를 사용중이지만 모든 필드에 대한 타입이 정해져 있지 않은 것으로 알고 있습니다. 
- 한 곳에 백엔드 API 반환값 타입을 정리한다면 프론트엔드의 API 코드를 타입스크립트로 전환시 큰 도움이 될 것입니다.
```[tasklist]
### Zod 익숙해지기
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/503
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/505
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/506
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/514
```

```[tasklist]
### Controller 스키마 Zod로 바꾸기
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/531
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/532
```

**Comment by scarf005** [comment]
v2 에서 진행
