### ISSUE TITLE
controller 에서 type 받아오기 (with zod)

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#506]
(30분 작업 + 10분 쉬는시간) * 3

```[tasklist]
### Tasks
- [x] zod 배워보기
- [x] 컨트롤러 파싱 zod로 바꾸기
- [x] 서로 코드 리뷰
```

```[tasklist]
### 컨트롤러 파싱
- [x] `books.controller` @scarf005
- [x] `users.controller` @jhMin95
- [x] `stocks.controller` @honeyl3ee
```
