### ISSUE TITLE
zod를 사용해 env 파싱 개선

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#509]
### 기능 설명

```[tasklist]
### Tasks
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/510
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/511
- [ ] 공식 문서에 환경 변수 설명 추가
```
