### ISSUE TITLE
☂️ 백엔드 컨트롤러 리팩터링

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#543]
```[tasklist]
### Tasks
- [ ] #542
- [x] `ts-rest` 적용
- [x] `GET route`부터 점진적으로 마이그레이션 진행
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/550
- [x] 모노레포로 전환?
- [ ] https://github.com/jiphyeonjeon-42/frontend/issues/472
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/533
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/577
```

https://github.com/andenacitelli/openapi-endpoint-trimmer
https://github.com/astahmer/openapi-zod-client

**Comment by scarf005** [comment]
세부 우산 이슈로 나누게 되어 닫기로 했습니다.
