### ISSUE TITLE
☂️ v2 리팩토링 - histories API

### ISSUE THREAD

**Issue by Yonaim** [jiphyeonjeon-42/backend#598]
### 기능 설명

히스토리 API에 ts-rest 적용하여 리팩토링이 필요합니다.
```[tasklist]
### Tasks
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/615
- [ ] contracts 작성
- [ ] controller 타입 추가
- [ ] service 타입 추가
- [ ] controller 구현
- [ ] service 구현
- [ ] impl.ts 작성
- [ ] https://github.com/jiphyeonjeon-42/backend/pull/599
```
