### ISSUE TITLE
☂️ 개발 가이드 문서화

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#611]
```[tasklist]
### Tasks
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/612
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/614
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/450
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/508
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/626
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/632
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/633
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/627
```
