### ISSUE TITLE
☂️ v2 리팩토링 - reservation API

### ISSUE THREAD

**Issue by Yonaim** [jiphyeonjeon-42/backend#621]
### 기능 설명

기존 api들에 대해 리팩토링 작업 수행 필요
```[tasklist]
### Tasks
- [x] 기존 v1 코드 분석 및 기능 파악
- [x] contracts 작성
- [ ] typeORM -> kysely 변환
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/798
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/793
```

**Comment by JeongJiHwan** [comment]
<img width="582" alt="image" src="https://github.com/jiphyeonjeon-42/backend/assets/47599349/d63df766-aa6d-4b5d-a960-0562069e935f">
