### ISSUE TITLE
☂️ v2 리팩토링 - auth API

### ISSUE THREAD

**Issue by Yonaim** [jiphyeonjeon-42/backend#622]
### 기능 설명

기존 api들에 대해 리팩토링 작업 수행 필요
```[tasklist]
### Tasks
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/686
- [ ] auth API controller 작성
- [ ] auth API service 작성
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/788
```

**Comment by jimin52** [comment]
https://www.npmjs.com/package/google-auth-library
이용해서 구글 소셜로그인 구현예정

**Comment by jimin52** [comment]
api endpoint 설계
```
POST `/api/v2/auth/login/intra`
intra 로 이동해서 인증

POST `/api/v2/auth/login/google`
google 로 이동해서 인증

POST `/api/v2/auth/token/intra`
intra 토큰 재발급

POST `/api/v2/auth/token/google`
google 토큰 재발급

GET `/api/v2/auth/me`
로그인 정보 얻어오기

POST `/api/v2/auth/logout`
로그아웃. 토큰 초기화

POST `/api/v2/auth/register/intra`
인트라 회원가입

POST `/api/v2/auth/register/google`
구글 회원가입
```
