### ISSUE TITLE
☂️ 개발 환경 구축

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#623]
```[tasklist]
### Tasks
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/624
- [ ] https://github.com/jiphyeonjeon-42/backend/pull/591
- [ ] CODEOWNERS 파일 추가
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/628
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/249
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/630
- [ ] https://github.com/jiphyeonjeon-42/backend/pull/634
```
