### ISSUE TITLE
☂️ V2 API 스펙 정리

### ISSUE THREAD

**Issue by nyj001012** [jiphyeonjeon-42/backend#649]
### 이슈 및 할 일 추가

```[tasklist]
### API 목록
- [ ] auth
- [ ] book-info-reviews
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/672
- [x] histories
- [ ] lendings
- [ ] reservations
- [x] reviews
- [x] stocks
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/685
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/650
```
