### ISSUE TITLE
☂️ v2를 별개 서버로 분리

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#651]
### 이슈 및 할 일 추가

```[tasklist]
### 할 일
- [ ] 별개 모노레포로 분리
- [ ] deno 프로젝트 구축
- [ ] 기존 v2 라우터 이전
- [ ] aws에 서버 호스팅
```
