### ISSUE TITLE
☂️ aws 개발 서버 호스팅

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#657]
# 개발 서버 운영 계획

크레딧 구매가 끝나 주말 내로 개발 서버를 AWS에 올릴수 있을 것 같습니다. 로컬 환경에서 develop 브랜치의 백엔드를 실행하는 것과 동일하게 동작하게(RDS 사용) 하는 것을 목표로 하고 있습니다.

## 추가 목적
1. 배포 전 실전 테스트
2. 매일 배포 실현
3. 프론트엔드 CI에서 playwright 테스트시 사용 가능

```[tasklist]
### 할일
- [x] 이슈로 만들기
- [x] aws 계정 MFA 생성
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/659
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/658
- [ ] https://github.com/jiphyeonjeon-42/frontend/issues/532
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/660
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/664
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/671
```
