### ISSUE TITLE
lightsail에 개발 서버 컨테이너 호스팅

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#658]
```[tasklist]
### Tasks
- [x] 예제 프로젝트 실행 테스트
- [x] 백엔드 저장소 실행 테스트
- [x] `.env` 추가
- [x] 프론트엔드에서 개발 서버 접근 가능 여부 확인
```
