### ISSUE TITLE
lightsail 보안 설정

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#659]
```[tasklist]
### Tasks
- [x] 포트 차단
- [x] IPv6 차단
- [x] CPU 버스트 알람 설정
- [x] 네트워크 트래픽 알람 설정
- [x] CPU 사용량 알람 설정
```
