### ISSUE TITLE
☂️ 검색 결과 미리보기

### ISSUE THREAD

**Issue by Jake1152** [jiphyeonjeon-42/backend#680]
```[tasklist]
### Tasks
- [x] local에서 테이블 생성 및 내용 추가 테스트
- [x] 검색용 table 구성(형태소 포함)
- [x] 검색결과 미리보기 쌩쿼리 작성
- [x] 생쿼리 결과 테스트
- [x] 검색결과 미리보기 api 구현 (router에서 전체 해결 버젼)
- [x] COUNT query 포함
- [x] 검색결과 미리보기 API Swagger 추가
- [x] 검색결과 미리보기 api 구현 (router(경로 매칭), cotroller(요청), service(로직) 분리버젼)
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/732
```
