### ISSUE TITLE
☂️ 인기 검색어 구현

### ISSUE THREAD

**Issue by Jiwon-Woo** [jiphyeonjeon-42/backend#695]
### 이슈 및 할 일 추가

```[tasklist]
### 할 일
- [x] 로그에서 검색어 데이터 추출
- [x] 검색어 저장용 Table 생성
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/710
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/713
```
