### ISSUE TITLE
☂️ zod 스키마 best practice 작성하기

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#708]
### 이슈 및 할 일 추가

```[tasklist]
### 할 일
- [ ] `docs/`에 zod 카테고리 만들기
- [ ] 이름 컨벤션 작성하기
- [ ] 스키마 재사용 팁 작성하기
```
