### ISSUE TITLE
☂️ 검색 기능 고도화를 위한 v1 API 수정

### ISSUE THREAD

**Issue by Jiwon-Woo** [jiphyeonjeon-42/backend#715]
### 이슈 및 할 일 추가

```[tasklist]
### 할 일
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/722
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/726
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/743
```
