### ISSUE TITLE
☂️ 검색 자동완성 고도화

### ISSUE THREAD

**Issue by Jiwon-Woo** [jiphyeonjeon-42/backend#734]
### 이슈 및 할 일 추가

```[tasklist]
### 할 일
- [ ] Full-Text 특수문제 처리 안되는 이슈, 원인 파악과 좀더 근본적인 해결 필요(현재는 특수문자 금지, c++같은 경우가 있어서 어떻게 할지 고민 필요)
- [ ] 도서명, 저자명, 출판사명 등 각 항목당 80자까지 허용이던 것  60자 등으로 축소(이유 DB에서 1개 칼럼에 255자까지 가능, 겹받침 닮 -> 'ㄷㅏㄹㅁ'으로 분리됨
- [ ] 검색결과 정렬 (e.g) '루비'라는 단어를 입력했을때 출판사 이름인 '루비페이퍼'가 먼저 나오는 것이 아니라 책 검색 결과가 상단에 표현되게 한다.
- [ ] 검색결과 모니터링 (일일이 검색할 때마다 저장하는 것 아닌, 어떻게 효율적으로 할 것인가?, 검색결과의 연관성을 어떻게 표현할 것인가?)
```
