### ISSUE TITLE
☂️ V2 전체 경로 정리

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/backend#768]
- #767 구체화

### 이슈 및 할 일 추가

```[tasklist]
### 할 일
- [ ] #701
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/773
- [ ] BookMeta 경로 정리
- [ ] https://github.com/jiphyeonjeon-42/backend/issues/776
```
